apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter-config
  labels:
    app: postgres-exporter
data:
  DATA_SOURCE_NAME: "postgresql://admin:admin123@postgres-0.postgres.default.svc.cluster.local:5432/postgresdb?sslmode=disable"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  labels:
    app: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9187'
    spec:
      containers:
      - name: postgres-exporter
        image: wrouesnel/postgres_exporter
        ports:
        - containerPort: 9187
        envFrom:
          - configMapRef:
              name: postgres-exporter-config

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  labels:
    app: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  ports:
    - protocol: TCP
      name: http
      port: 9187
      targetPort: 9187
