apiVersion: v1
kind: ConfigMap
metadata:
  namespace:  infra
  name: nexus-properties-cm
data:
  nexus.properties: |
    # Jetty section
    # application-port=8081
    # application-host=0.0.0.0
    # nexus-args=${jetty.etc}/jetty.xml,${jetty.etc}/jetty-http.xml,${jetty.etc}/jetty-requestlog.xml
    nexus-context-path=/infra/nexus
    # Nexus section
    # nexus-edition=nexus-pro-edition
    # nexus-features=\
    #  nexus-pro-feature
    # nexus.hazelcast.discovery.isEnabled=true
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nexus
  namespace: infra
spec:
  replicas: 1
  serviceName: nexus
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      initContainers:
      - name: change-ownership-container
        image: busybox
        command: ["/bin/chown","-R","200:200", "/nexus-data"]
        #command: ["/bin/sh","-c"]
        #args: ["adduser --disabled-password --no-create-home nexus; /bin/chown -R nexus:nexus /nexus-data"]
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
      containers:
      - name: nexus3
        image: sonatype/nexus3:latest
        securityContext:
          runAsUser: 200
          runAsGroup: 200
        #  runAsNonRoot: true
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: "4Gi"
            cpu: "1000m"
          requests:
            memory: "2Gi"
            cpu: "500m"
        #env:
        #- name: NEXUS_CONTEXT
        #  value: nexus
        ports:
          - containerPort: 8081
        volumeMounts:
          - name: nexus-data
            mountPath: /nexus-data
          - name: nexus-properties
            mountPath: /nexus-data/etc/nexus.properties
            subPath: nexus.properties 
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: pvc-nexus-data
        - name: nexus-properties
          configMap:
            name: nexus-properties-cm
