kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nexus-data
  namespace: infra
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
