apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: infra
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: /
      prometheus.io/port: '8081'
spec:
  selector:
    app: nexus
  ports:
  - port: 8081
    targetPort: 8081
