annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Update SonarQube to 9.8.0"
    - kind: fixed
      description: "Update the postgresql chart's repository"
    - kind: changed
      description: "Refactor Ingress to be compatible with static compatibility test and 1.19 minimum requirement"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: sonarqube
      image: sonarqube:9.8.0-community
  artifacthub.io/links: |
    - name: support
      url: https://community.sonarsource.com/
    - name: Chart Source
      url: https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube
apiVersion: v2
appVersion: 9.8.0
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
  version: 10.15.0
- condition: nginx.enabled
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.0.13
description: SonarQube offers Code Quality and Code Security analysis for up to 27
  languages. Find Bugs, Vulnerabilities, Security Hotspots and Code Smells throughout
  your workflow.
home: https://www.sonarqube.org/
icon: https://www.sonarqube.org/assets/logo-31ad3115b1b4b120f3d1efd63e6b13ac9f1f89437f0cf6881cc4d8b5603a52b4.svg
keywords:
- coverage
- security
- code
- quality
kubeVersion: '>= 1.19.0-0'
maintainers:
- email: leo.geoffroy+helm@sonarsource.com
  name: leo-geoffroy-sonarsource
name: sonarqube
sources:
- https://github.com/SonarSource/docker-sonarqube
- https://github.com/SonarSource/sonarqube
type: application
version: 7.0.0+449
