apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server
  namespace: default
  labels: 
    app: spark-history-server 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-history-server
  template:
    metadata:
      name: spark-history-server
      labels:
        app: spark-history-server
    spec:
      serviceAccountName: spark
      containers:
        - name: spark-history-server
          image: manju369/spark-3.2.0-bin-hadoop3.2-gcs:2
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
          command:
            -  "/usr/lib/jvm/java-8-openjdk-amd64/bin/java"
          args:
            - "-cp" 
            - "/opt/spark/conf/:/opt/spark/jars/*"
            - "-Xmx1g"
            - "org.apache.spark.deploy.history.HistoryServer"
          ports:
            - name: http
              protocol: TCP
              containerPort: 18080
          volumeMounts:
            - name: spark-defaults-config-file
              mountPath: /opt/spark/conf/
            - name: spark-gcs-bucket-secret
              mountPath: /mnt/secrets/
              readOnly: true
      volumes:
      - name: spark-defaults-config-file
        configMap:
          defaultMode: 0777
          name: spark-defaults-configmap
      - name: spark-gcs-bucket-secret
        secret:
          secretName: gcs-bq
