apiVersion: v1
kind: Service
metadata:
  name: spark-history-server-svc
  labels:
    app: spark-history-server-svc
spec:
  selector:
    app: spark-history-server
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 18080
      targetPort: 18080
