apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-config
  labels:
    app: nifi-config
data:
  NIFI_WEB_HTTP_HOST: "0.0.0.0"
  NIFI_WEB_HTTP_PORT: "9080"
  NIFI_JVM_HEAP_INIT: "512m"
  NIFI_JVM_HEAP_MAX: "512m"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi-app
  labels:
    app: nifi-server
spec:
  serviceName: nifi-service
  selector:
    matchLabels:
      app: nifi-server
  template:
    metadata:
      labels:
        app: nifi-server
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: fetch
          image: mwendler/wget
          imagePullPolicy: IfNotPresent
          command:  [ "/bin/sh","-c","wget --no-check-certificate https://jdbc.postgresql.org/download/postgresql-42.2.10.jar -O /opt/nifi/nifi-drivers/postgresql-42.2.10.jar" ]
          volumeMounts:
            - mountPath: /opt/nifi/nifi-drivers/
              name: nifi-drivers
      containers:
        - name: nifi-app
          image: apache/nifi:1.12.1
          ports:
          - containerPort: 9080
          envFrom:
          - configMapRef:
              name: nifi-config
          volumeMounts:
            - name: nifi-flow-file
              mountPath: /opt/nifi/nifi-current/data/
            - name: nifi-properties-file
              mountPath: /opt/nifi/nifi-current/kubeconfig
            - name: nifi-drivers
              mountPath: /opt/nifi/nifi-drivers/
          lifecycle:
            postStart:
              exec:
                command:
                  - bash
                  - -c
                  - |
                    cp -a /opt/nifi/nifi-current/kubeconfig/. /opt/nifi/nifi-current/conf
      volumes:
      - name: nifi-properties-file
        configMap:
          defaultMode: 0777
          name: nifi-properties
      - name: nifi-flow-file
        persistentVolumeClaim:
          claimName: nifi-standalone-pvc
      - name: nifi-drivers
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nifi-service
  labels:
    app: nifi-service
spec:
  selector:
    app: nifi-server
  ports:
    - protocol: TCP
      name: http
      port: 9080
      targetPort: 9080

---
apiVersion: v1
kind: Service
metadata:
  name: nifi-nodeport-service
  labels:
    app: nifi-nodeport-service
spec:
  selector:
    app: nifi-server
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 9080
      targetPort: 9080
status:
  loadBalancer: {}
      
  ##Reference - https://stackoverflow.com/questions/51786114/changing-configuration-in-running-kubernetes-pod
  #           - https://www.magalix.com/blog/kubernetes-patterns-the-init-container-pattern
  #           - https://stackoverflow.com/questions/33979501/kubernetes-passing-multiple-commands-to-the-container
