apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-elasticsearch-disk
  namespace: infra
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
