apiVersion: apps/v1
kind: Deployment
metadata: 
  name: prometheus-deployment-app
  labels:
    app: prometheus-server
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: prometheus-app
          image: prom/prometheus
          args:
             - "--storage.tsdb.retention.time=8h"
             - "--config.file=/etc/prometheus/prometheus.yml"
             - "--storage.tsdb.path=/prometheus/"
             - "--web.external-url=http://localhost:9090/dumbworks/prometheus/"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      initContainers:
      - name: change-ownership-container
        image: busybox
        command: ["/bin/chown","-R","1000:1000", "/prometheus"]
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - name: prometheus-storage-volume
          mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf

        - name: prometheus-storage-volume
          persistentVolumeClaim:
            claimName: prometheus-standalone-pvc  
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 9090
      port: 9090
  selector:
    app: prometheus-server
