kind: Service
apiVersion: v1
metadata:
  name: ingress-kibana
spec:
  type: ExternalName
  externalName: kibana.infra.svc.cluster.local

---
kind: Service
apiVersion: v1
metadata:
  name: ingress-jenkins
spec:
  type: ExternalName
  externalName: jenkins-ext.jenkins.svc.cluster.local

---
kind: Service
apiVersion: v1
metadata:
  name: ingress-nexus
spec:
  type: ExternalName
  externalName: nexus.infra.svc.cluster.local

---
kind: Service
apiVersion: v1
metadata:
  name: ingress-jupyter
spec:
  type: ExternalName
  externalName: proxy-public.dev.svc.cluster.local
