apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-standalone-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 15Gi
