kind: Deployment
#kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: jenkins-master
  namespace: jenkins
  labels:
    app: jenkins-master
spec:
  replicas: 1
  #serviceName: jenkins-ui
  selector:
    matchLabels:
      app: jenkins-master
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      initContainers:
      - name: change-ownership-container
        image: busybox
        command: ["/bin/sh", "-c"]
        args: 
          - /bin/chown -R 1000:1000 /var/jenkins_home ;
            /bin/chmod 777 /var/run/docker.sock ;
            echo "init done" ;         
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - mountPath: /var/run/docker.sock
          name: docker-sock
      containers:
      - name: jenkins
        image: manju369/jenkins:2.356-jdk8
        imagePullPolicy: Always
        ports:
        - name: httpport
          containerPort: 8080
        - name: jnlpport
          containerPort: 50000
        readinessProbe:
          httpGet:
            path: /jenkins/login
            port: 8080
          initialDelaySeconds: 300
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        env:
        - name: JENKINS_OPTS
          value: "--prefix=/jenkins --httpListenAddress=0.0.0.0"
        resources:
          limits:
            cpu: 500m
            memory: 1400Mi
          requests:
            cpu: 300m
            memory: 1200Mi
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        - mountPath: /var/run/docker.sock
          name: docker-sock
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: pvc-jenkins-home
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          #type: File
