---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-ext
  namespace: jenkins
spec:
  selector:
    app: jenkins-master
  ports:
    - name: httpport
      port: 8080
      targetPort: 8080
    - name: jnlpport
      port: 50000
      targetPort: 50000
