kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: airflow-logs-storage-class
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: pd-standard
  fstype: ext4
